# Generated by Django 5.2.5 on 2025-08-29 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=200)),
                ('passout_year', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('handle', models.CharField(max_length=64, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('expected_complexity', models.CharField(choices=[('O(1)', 'O(1)'), ('O(log n)', 'O(log n)'), ('O(n)', 'O(n)'), ('O(n log n)', 'O(n log n)'), ('O(n^2)', 'O(n^2)'), ('O(n^3)', 'O(n^3)'), ('O(2^n)', 'O(2^n)')], default='O(n)', max_length=20)),
                ('mem_limit_mb', models.PositiveIntegerField(default=256)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='accounts.contest')),
            ],
            options={
                'unique_together': {('contest', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=30)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('inferred_complexity', models.CharField(default='O(n)', max_length=20)),
                ('fit_error', models.FloatField(default=0.0)),
                ('const_C', models.FloatField(default=1.0)),
                ('peak_mem_mb', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.participant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='accounts.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreboardRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_scores', models.JSONField(default=dict)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.participant')),
            ],
            options={
                'unique_together': {('contest', 'participant')},
            },
        ),
    ]
