# Generated by Django 5.2.5 on 2025-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='mem_limit_mb',
            new_name='cpp_mem_limit_mb',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='expected_complexity',
        ),
        migrations.AddField(
            model_name='problem',
            name='cpp_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_mem_limit_mb',
            field=models.PositiveIntegerField(default=256),
        ),
    ]
