# Generated by Django 5.2.5 on 2025-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_mem_limit_mb_problem_cpp_mem_limit_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
