# Generated by Django 5.2.5 on 2025-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_problem_slug_problem_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
