# Generated by Django 5.2.5 on 2025-09-05 08:25

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_participant_is_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.testcase_upload_path),
        ),
        migrations.AddField(
            model_name='testcase',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
