# Generated by Django 5.2.5 on 2025-09-05 08:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_testcase_file_testcase_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='testcase',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='file',
            field=models.FileField(default='python', upload_to=accounts.models.testcase_upload_path),
            preserve_default=False,
        ),
    ]
