# Generated by Django 5.2.5 on 2025-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_testcase_expected_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='cpp_answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='cpp_mem_limit_mb',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='python_answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='python_mem_limit_mb',
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
